### PR TITLE
Changed: DeleteCommand now uses selection snapshot.

### LINKED ISSUE #10: Use selection snapshot instead of ModelDocument#selection
At the moment, `DeleteCommand` operates on "original" `engine.model.Document#selection`. It passes it to composer method which results in incorrect modifications of document selection.

Instead, it should take snapshot of document selection using `DocumentSelection#getSnapshot` and use this when calling composer methods.

This issue assumes merging PR from `ckedtior5-engine`: https://github.com/ckeditor/ckeditor5-engine/pull/505

### PR DESCRIPTION
**Pull request by scofalik**
Fixes #10.

### CODE REVIEW

**Comment by Reinmar** [comment]
I've just merged https://github.com/ckeditor/ckeditor5-delete/pull/9 and there are conflicts which need to be updated. There are new test cases in `deletecommand-integration.js` that needs to be updated as well.

**Comment by scofalik** [comment]
https://github.com/ckeditor/ckeditor5-engine/issues/329 is fixed on master so we can merge this. I rebased with current master and resolved conflicts and also pushed an additional test + slight tweak in character counting. Unfortunately (or maybe fortunately?) with this tweak element removal is not counted to buffer, so merging two `<p>`s does not change buffer size. Still, I think this is better than wrongly using `shallow` option, where only nodes from the "first parent" were counted.

**Comment by Reinmar** [comment]
I think that this is acceptable solution. It's simple and you wouldn't figure out that block merging wasn't counted as a change. If you have steps like 20 items (the default) you're not gonna feel this.

**Comment by scofalik** [comment]
I know that this is already merged, but the solution also counts this middle `<p>` as one node:
`<p>a[bc</p><p>xyz</p><p>fo]p</p>`.

If you think that we (will) need to work on this case, please add follow-up issue,

**Pull request merged**
